// Code generated by ent, DO NOT EDIT.

package subscriptionorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldID, id))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldOrderNo, v))
}

// TradeNo applies equality check predicate on the "trade_no" field. It's identical to TradeNoEQ.
func TradeNo(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldTradeNo, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldGroupID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldAmount, v))
}

// OriginalPrice applies equality check predicate on the "original_price" field. It's identical to OriginalPriceEQ.
func OriginalPrice(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldOriginalPrice, v))
}

// DiscountAmount applies equality check predicate on the "discount_amount" field. It's identical to DiscountAmountEQ.
func DiscountAmount(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldDiscountAmount, v))
}

// PaymentMethod applies equality check predicate on the "payment_method" field. It's identical to PaymentMethodEQ.
func PaymentMethod(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaymentMethod, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldStatus, v))
}

// NotifyData applies equality check predicate on the "notify_data" field. It's identical to NotifyDataEQ.
func NotifyData(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldNotifyData, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaidAt, v))
}

// ExpiredAt applies equality check predicate on the "expired_at" field. It's identical to ExpiredAtEQ.
func ExpiredAt(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldExpiredAt, v))
}

// ActivatedAt applies equality check predicate on the "activated_at" field. It's identical to ActivatedAtEQ.
func ActivatedAt(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldActivatedAt, v))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldSubscriptionID, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContainsFold(FieldOrderNo, v))
}

// TradeNoEQ applies the EQ predicate on the "trade_no" field.
func TradeNoEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldTradeNo, v))
}

// TradeNoNEQ applies the NEQ predicate on the "trade_no" field.
func TradeNoNEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldTradeNo, v))
}

// TradeNoIn applies the In predicate on the "trade_no" field.
func TradeNoIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldTradeNo, vs...))
}

// TradeNoNotIn applies the NotIn predicate on the "trade_no" field.
func TradeNoNotIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldTradeNo, vs...))
}

// TradeNoGT applies the GT predicate on the "trade_no" field.
func TradeNoGT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldTradeNo, v))
}

// TradeNoGTE applies the GTE predicate on the "trade_no" field.
func TradeNoGTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldTradeNo, v))
}

// TradeNoLT applies the LT predicate on the "trade_no" field.
func TradeNoLT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldTradeNo, v))
}

// TradeNoLTE applies the LTE predicate on the "trade_no" field.
func TradeNoLTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldTradeNo, v))
}

// TradeNoContains applies the Contains predicate on the "trade_no" field.
func TradeNoContains(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContains(FieldTradeNo, v))
}

// TradeNoHasPrefix applies the HasPrefix predicate on the "trade_no" field.
func TradeNoHasPrefix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasPrefix(FieldTradeNo, v))
}

// TradeNoHasSuffix applies the HasSuffix predicate on the "trade_no" field.
func TradeNoHasSuffix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasSuffix(FieldTradeNo, v))
}

// TradeNoIsNil applies the IsNil predicate on the "trade_no" field.
func TradeNoIsNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIsNull(FieldTradeNo))
}

// TradeNoNotNil applies the NotNil predicate on the "trade_no" field.
func TradeNoNotNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotNull(FieldTradeNo))
}

// TradeNoEqualFold applies the EqualFold predicate on the "trade_no" field.
func TradeNoEqualFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEqualFold(FieldTradeNo, v))
}

// TradeNoContainsFold applies the ContainsFold predicate on the "trade_no" field.
func TradeNoContainsFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContainsFold(FieldTradeNo, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldGroupID, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldAmount, v))
}

// OriginalPriceEQ applies the EQ predicate on the "original_price" field.
func OriginalPriceEQ(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldOriginalPrice, v))
}

// OriginalPriceNEQ applies the NEQ predicate on the "original_price" field.
func OriginalPriceNEQ(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldOriginalPrice, v))
}

// OriginalPriceIn applies the In predicate on the "original_price" field.
func OriginalPriceIn(vs ...float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldOriginalPrice, vs...))
}

// OriginalPriceNotIn applies the NotIn predicate on the "original_price" field.
func OriginalPriceNotIn(vs ...float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldOriginalPrice, vs...))
}

// OriginalPriceGT applies the GT predicate on the "original_price" field.
func OriginalPriceGT(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldOriginalPrice, v))
}

// OriginalPriceGTE applies the GTE predicate on the "original_price" field.
func OriginalPriceGTE(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldOriginalPrice, v))
}

// OriginalPriceLT applies the LT predicate on the "original_price" field.
func OriginalPriceLT(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldOriginalPrice, v))
}

// OriginalPriceLTE applies the LTE predicate on the "original_price" field.
func OriginalPriceLTE(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldOriginalPrice, v))
}

// DiscountAmountEQ applies the EQ predicate on the "discount_amount" field.
func DiscountAmountEQ(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldDiscountAmount, v))
}

// DiscountAmountNEQ applies the NEQ predicate on the "discount_amount" field.
func DiscountAmountNEQ(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldDiscountAmount, v))
}

// DiscountAmountIn applies the In predicate on the "discount_amount" field.
func DiscountAmountIn(vs ...float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldDiscountAmount, vs...))
}

// DiscountAmountNotIn applies the NotIn predicate on the "discount_amount" field.
func DiscountAmountNotIn(vs ...float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldDiscountAmount, vs...))
}

// DiscountAmountGT applies the GT predicate on the "discount_amount" field.
func DiscountAmountGT(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldDiscountAmount, v))
}

// DiscountAmountGTE applies the GTE predicate on the "discount_amount" field.
func DiscountAmountGTE(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldDiscountAmount, v))
}

// DiscountAmountLT applies the LT predicate on the "discount_amount" field.
func DiscountAmountLT(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldDiscountAmount, v))
}

// DiscountAmountLTE applies the LTE predicate on the "discount_amount" field.
func DiscountAmountLTE(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldDiscountAmount, v))
}

// PaymentMethodEQ applies the EQ predicate on the "payment_method" field.
func PaymentMethodEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaymentMethod, v))
}

// PaymentMethodNEQ applies the NEQ predicate on the "payment_method" field.
func PaymentMethodNEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldPaymentMethod, v))
}

// PaymentMethodIn applies the In predicate on the "payment_method" field.
func PaymentMethodIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldPaymentMethod, vs...))
}

// PaymentMethodNotIn applies the NotIn predicate on the "payment_method" field.
func PaymentMethodNotIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldPaymentMethod, vs...))
}

// PaymentMethodGT applies the GT predicate on the "payment_method" field.
func PaymentMethodGT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldPaymentMethod, v))
}

// PaymentMethodGTE applies the GTE predicate on the "payment_method" field.
func PaymentMethodGTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldPaymentMethod, v))
}

// PaymentMethodLT applies the LT predicate on the "payment_method" field.
func PaymentMethodLT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldPaymentMethod, v))
}

// PaymentMethodLTE applies the LTE predicate on the "payment_method" field.
func PaymentMethodLTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldPaymentMethod, v))
}

// PaymentMethodContains applies the Contains predicate on the "payment_method" field.
func PaymentMethodContains(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContains(FieldPaymentMethod, v))
}

// PaymentMethodHasPrefix applies the HasPrefix predicate on the "payment_method" field.
func PaymentMethodHasPrefix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasPrefix(FieldPaymentMethod, v))
}

// PaymentMethodHasSuffix applies the HasSuffix predicate on the "payment_method" field.
func PaymentMethodHasSuffix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasSuffix(FieldPaymentMethod, v))
}

// PaymentMethodEqualFold applies the EqualFold predicate on the "payment_method" field.
func PaymentMethodEqualFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEqualFold(FieldPaymentMethod, v))
}

// PaymentMethodContainsFold applies the ContainsFold predicate on the "payment_method" field.
func PaymentMethodContainsFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContainsFold(FieldPaymentMethod, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContainsFold(FieldStatus, v))
}

// NotifyDataEQ applies the EQ predicate on the "notify_data" field.
func NotifyDataEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldNotifyData, v))
}

// NotifyDataNEQ applies the NEQ predicate on the "notify_data" field.
func NotifyDataNEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldNotifyData, v))
}

// NotifyDataIn applies the In predicate on the "notify_data" field.
func NotifyDataIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldNotifyData, vs...))
}

// NotifyDataNotIn applies the NotIn predicate on the "notify_data" field.
func NotifyDataNotIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldNotifyData, vs...))
}

// NotifyDataGT applies the GT predicate on the "notify_data" field.
func NotifyDataGT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldNotifyData, v))
}

// NotifyDataGTE applies the GTE predicate on the "notify_data" field.
func NotifyDataGTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldNotifyData, v))
}

// NotifyDataLT applies the LT predicate on the "notify_data" field.
func NotifyDataLT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldNotifyData, v))
}

// NotifyDataLTE applies the LTE predicate on the "notify_data" field.
func NotifyDataLTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldNotifyData, v))
}

// NotifyDataContains applies the Contains predicate on the "notify_data" field.
func NotifyDataContains(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContains(FieldNotifyData, v))
}

// NotifyDataHasPrefix applies the HasPrefix predicate on the "notify_data" field.
func NotifyDataHasPrefix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasPrefix(FieldNotifyData, v))
}

// NotifyDataHasSuffix applies the HasSuffix predicate on the "notify_data" field.
func NotifyDataHasSuffix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasSuffix(FieldNotifyData, v))
}

// NotifyDataIsNil applies the IsNil predicate on the "notify_data" field.
func NotifyDataIsNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIsNull(FieldNotifyData))
}

// NotifyDataNotNil applies the NotNil predicate on the "notify_data" field.
func NotifyDataNotNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotNull(FieldNotifyData))
}

// NotifyDataEqualFold applies the EqualFold predicate on the "notify_data" field.
func NotifyDataEqualFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEqualFold(FieldNotifyData, v))
}

// NotifyDataContainsFold applies the ContainsFold predicate on the "notify_data" field.
func NotifyDataContainsFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContainsFold(FieldNotifyData, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotNull(FieldPaidAt))
}

// ExpiredAtEQ applies the EQ predicate on the "expired_at" field.
func ExpiredAtEQ(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldExpiredAt, v))
}

// ExpiredAtNEQ applies the NEQ predicate on the "expired_at" field.
func ExpiredAtNEQ(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldExpiredAt, v))
}

// ExpiredAtIn applies the In predicate on the "expired_at" field.
func ExpiredAtIn(vs ...time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldExpiredAt, vs...))
}

// ExpiredAtNotIn applies the NotIn predicate on the "expired_at" field.
func ExpiredAtNotIn(vs ...time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldExpiredAt, vs...))
}

// ExpiredAtGT applies the GT predicate on the "expired_at" field.
func ExpiredAtGT(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldExpiredAt, v))
}

// ExpiredAtGTE applies the GTE predicate on the "expired_at" field.
func ExpiredAtGTE(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldExpiredAt, v))
}

// ExpiredAtLT applies the LT predicate on the "expired_at" field.
func ExpiredAtLT(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldExpiredAt, v))
}

// ExpiredAtLTE applies the LTE predicate on the "expired_at" field.
func ExpiredAtLTE(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldExpiredAt, v))
}

// ExpiredAtIsNil applies the IsNil predicate on the "expired_at" field.
func ExpiredAtIsNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIsNull(FieldExpiredAt))
}

// ExpiredAtNotNil applies the NotNil predicate on the "expired_at" field.
func ExpiredAtNotNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotNull(FieldExpiredAt))
}

// ActivatedAtEQ applies the EQ predicate on the "activated_at" field.
func ActivatedAtEQ(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldActivatedAt, v))
}

// ActivatedAtNEQ applies the NEQ predicate on the "activated_at" field.
func ActivatedAtNEQ(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldActivatedAt, v))
}

// ActivatedAtIn applies the In predicate on the "activated_at" field.
func ActivatedAtIn(vs ...time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldActivatedAt, vs...))
}

// ActivatedAtNotIn applies the NotIn predicate on the "activated_at" field.
func ActivatedAtNotIn(vs ...time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldActivatedAt, vs...))
}

// ActivatedAtGT applies the GT predicate on the "activated_at" field.
func ActivatedAtGT(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldActivatedAt, v))
}

// ActivatedAtGTE applies the GTE predicate on the "activated_at" field.
func ActivatedAtGTE(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldActivatedAt, v))
}

// ActivatedAtLT applies the LT predicate on the "activated_at" field.
func ActivatedAtLT(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldActivatedAt, v))
}

// ActivatedAtLTE applies the LTE predicate on the "activated_at" field.
func ActivatedAtLTE(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldActivatedAt, v))
}

// ActivatedAtIsNil applies the IsNil predicate on the "activated_at" field.
func ActivatedAtIsNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIsNull(FieldActivatedAt))
}

// ActivatedAtNotNil applies the NotNil predicate on the "activated_at" field.
func ActivatedAtNotNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotNull(FieldActivatedAt))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDGT applies the GT predicate on the "subscription_id" field.
func SubscriptionIDGT(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldSubscriptionID, v))
}

// SubscriptionIDGTE applies the GTE predicate on the "subscription_id" field.
func SubscriptionIDGTE(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldSubscriptionID, v))
}

// SubscriptionIDLT applies the LT predicate on the "subscription_id" field.
func SubscriptionIDLT(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldSubscriptionID, v))
}

// SubscriptionIDLTE applies the LTE predicate on the "subscription_id" field.
func SubscriptionIDLTE(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldSubscriptionID, v))
}

// SubscriptionIDIsNil applies the IsNil predicate on the "subscription_id" field.
func SubscriptionIDIsNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIsNull(FieldSubscriptionID))
}

// SubscriptionIDNotNil applies the NotNil predicate on the "subscription_id" field.
func SubscriptionIDNotNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotNull(FieldSubscriptionID))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionOrder) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionOrder) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionOrder) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.NotPredicates(p))
}
