// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SubscriptionOrderCreate is the builder for creating a SubscriptionOrder entity.
type SubscriptionOrderCreate struct {
	config
	mutation *SubscriptionOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrderNo sets the "order_no" field.
func (_c *SubscriptionOrderCreate) SetOrderNo(v string) *SubscriptionOrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetTradeNo sets the "trade_no" field.
func (_c *SubscriptionOrderCreate) SetTradeNo(v string) *SubscriptionOrderCreate {
	_c.mutation.SetTradeNo(v)
	return _c
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableTradeNo(v *string) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetTradeNo(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SubscriptionOrderCreate) SetUserID(v int64) *SubscriptionOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *SubscriptionOrderCreate) SetGroupID(v int64) *SubscriptionOrderCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *SubscriptionOrderCreate) SetAmount(v float64) *SubscriptionOrderCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetOriginalPrice sets the "original_price" field.
func (_c *SubscriptionOrderCreate) SetOriginalPrice(v float64) *SubscriptionOrderCreate {
	_c.mutation.SetOriginalPrice(v)
	return _c
}

// SetDiscountAmount sets the "discount_amount" field.
func (_c *SubscriptionOrderCreate) SetDiscountAmount(v float64) *SubscriptionOrderCreate {
	_c.mutation.SetDiscountAmount(v)
	return _c
}

// SetNillableDiscountAmount sets the "discount_amount" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableDiscountAmount(v *float64) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetDiscountAmount(*v)
	}
	return _c
}

// SetPaymentMethod sets the "payment_method" field.
func (_c *SubscriptionOrderCreate) SetPaymentMethod(v string) *SubscriptionOrderCreate {
	_c.mutation.SetPaymentMethod(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubscriptionOrderCreate) SetStatus(v string) *SubscriptionOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableStatus(v *string) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNotifyData sets the "notify_data" field.
func (_c *SubscriptionOrderCreate) SetNotifyData(v string) *SubscriptionOrderCreate {
	_c.mutation.SetNotifyData(v)
	return _c
}

// SetNillableNotifyData sets the "notify_data" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableNotifyData(v *string) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetNotifyData(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionOrderCreate) SetCreatedAt(v time.Time) *SubscriptionOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *SubscriptionOrderCreate) SetPaidAt(v time.Time) *SubscriptionOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillablePaidAt(v *time.Time) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetExpiredAt sets the "expired_at" field.
func (_c *SubscriptionOrderCreate) SetExpiredAt(v time.Time) *SubscriptionOrderCreate {
	_c.mutation.SetExpiredAt(v)
	return _c
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableExpiredAt(v *time.Time) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetExpiredAt(*v)
	}
	return _c
}

// SetActivatedAt sets the "activated_at" field.
func (_c *SubscriptionOrderCreate) SetActivatedAt(v time.Time) *SubscriptionOrderCreate {
	_c.mutation.SetActivatedAt(v)
	return _c
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableActivatedAt(v *time.Time) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetActivatedAt(*v)
	}
	return _c
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *SubscriptionOrderCreate) SetSubscriptionID(v int64) *SubscriptionOrderCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableSubscriptionID(v *int64) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetSubscriptionID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SubscriptionOrderCreate) SetUser(v *User) *SubscriptionOrderCreate {
	return _c.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *SubscriptionOrderCreate) SetGroup(v *Group) *SubscriptionOrderCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the SubscriptionOrderMutation object of the builder.
func (_c *SubscriptionOrderCreate) Mutation() *SubscriptionOrderMutation {
	return _c.mutation
}

// Save creates the SubscriptionOrder in the database.
func (_c *SubscriptionOrderCreate) Save(ctx context.Context) (*SubscriptionOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionOrderCreate) SaveX(ctx context.Context) *SubscriptionOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionOrderCreate) defaults() {
	if _, ok := _c.mutation.DiscountAmount(); !ok {
		v := subscriptionorder.DefaultDiscountAmount
		_c.mutation.SetDiscountAmount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := subscriptionorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionOrderCreate) check() error {
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "SubscriptionOrder.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := subscriptionorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TradeNo(); ok {
		if err := subscriptionorder.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.trade_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SubscriptionOrder.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "SubscriptionOrder.group_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "SubscriptionOrder.amount"`)}
	}
	if _, ok := _c.mutation.OriginalPrice(); !ok {
		return &ValidationError{Name: "original_price", err: errors.New(`ent: missing required field "SubscriptionOrder.original_price"`)}
	}
	if _, ok := _c.mutation.DiscountAmount(); !ok {
		return &ValidationError{Name: "discount_amount", err: errors.New(`ent: missing required field "SubscriptionOrder.discount_amount"`)}
	}
	if _, ok := _c.mutation.PaymentMethod(); !ok {
		return &ValidationError{Name: "payment_method", err: errors.New(`ent: missing required field "SubscriptionOrder.payment_method"`)}
	}
	if v, ok := _c.mutation.PaymentMethod(); ok {
		if err := subscriptionorder.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.payment_method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SubscriptionOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := subscriptionorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionOrder.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SubscriptionOrder.user"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "SubscriptionOrder.group"`)}
	}
	return nil
}

func (_c *SubscriptionOrderCreate) sqlSave(ctx context.Context) (*SubscriptionOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionOrderCreate) createSpec() (*SubscriptionOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionorder.Table, sqlgraph.NewFieldSpec(subscriptionorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(subscriptionorder.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.TradeNo(); ok {
		_spec.SetField(subscriptionorder.FieldTradeNo, field.TypeString, value)
		_node.TradeNo = &value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(subscriptionorder.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.OriginalPrice(); ok {
		_spec.SetField(subscriptionorder.FieldOriginalPrice, field.TypeFloat64, value)
		_node.OriginalPrice = value
	}
	if value, ok := _c.mutation.DiscountAmount(); ok {
		_spec.SetField(subscriptionorder.FieldDiscountAmount, field.TypeFloat64, value)
		_node.DiscountAmount = value
	}
	if value, ok := _c.mutation.PaymentMethod(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentMethod, field.TypeString, value)
		_node.PaymentMethod = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subscriptionorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.NotifyData(); ok {
		_spec.SetField(subscriptionorder.FieldNotifyData, field.TypeString, value)
		_node.NotifyData = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(subscriptionorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.ExpiredAt(); ok {
		_spec.SetField(subscriptionorder.FieldExpiredAt, field.TypeTime, value)
		_node.ExpiredAt = &value
	}
	if value, ok := _c.mutation.ActivatedAt(); ok {
		_spec.SetField(subscriptionorder.FieldActivatedAt, field.TypeTime, value)
		_node.ActivatedAt = &value
	}
	if value, ok := _c.mutation.SubscriptionID(); ok {
		_spec.SetField(subscriptionorder.FieldSubscriptionID, field.TypeInt64, value)
		_node.SubscriptionID = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.UserTable,
			Columns: []string{subscriptionorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.GroupTable,
			Columns: []string{subscriptionorder.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionOrder.Create().
//		SetOrderNo(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionOrderUpsert) {
//			SetOrderNo(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionOrderCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionOrderUpsertOne {
	_c.conflict = opts
	return &SubscriptionOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionOrderCreate) OnConflictColumns(columns ...string) *SubscriptionOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionOrderUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionOrderUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionOrder node.
	SubscriptionOrderUpsertOne struct {
		create *SubscriptionOrderCreate
	}

	// SubscriptionOrderUpsert is the "OnConflict" setter.
	SubscriptionOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrderNo sets the "order_no" field.
func (u *SubscriptionOrderUpsert) SetOrderNo(v string) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateOrderNo() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldOrderNo)
	return u
}

// SetTradeNo sets the "trade_no" field.
func (u *SubscriptionOrderUpsert) SetTradeNo(v string) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldTradeNo, v)
	return u
}

// UpdateTradeNo sets the "trade_no" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateTradeNo() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldTradeNo)
	return u
}

// ClearTradeNo clears the value of the "trade_no" field.
func (u *SubscriptionOrderUpsert) ClearTradeNo() *SubscriptionOrderUpsert {
	u.SetNull(subscriptionorder.FieldTradeNo)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionOrderUpsert) SetUserID(v int64) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateUserID() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldUserID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionOrderUpsert) SetGroupID(v int64) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateGroupID() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldGroupID)
	return u
}

// SetAmount sets the "amount" field.
func (u *SubscriptionOrderUpsert) SetAmount(v float64) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateAmount() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *SubscriptionOrderUpsert) AddAmount(v float64) *SubscriptionOrderUpsert {
	u.Add(subscriptionorder.FieldAmount, v)
	return u
}

// SetOriginalPrice sets the "original_price" field.
func (u *SubscriptionOrderUpsert) SetOriginalPrice(v float64) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldOriginalPrice, v)
	return u
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateOriginalPrice() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldOriginalPrice)
	return u
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *SubscriptionOrderUpsert) AddOriginalPrice(v float64) *SubscriptionOrderUpsert {
	u.Add(subscriptionorder.FieldOriginalPrice, v)
	return u
}

// SetDiscountAmount sets the "discount_amount" field.
func (u *SubscriptionOrderUpsert) SetDiscountAmount(v float64) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldDiscountAmount, v)
	return u
}

// UpdateDiscountAmount sets the "discount_amount" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateDiscountAmount() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldDiscountAmount)
	return u
}

// AddDiscountAmount adds v to the "discount_amount" field.
func (u *SubscriptionOrderUpsert) AddDiscountAmount(v float64) *SubscriptionOrderUpsert {
	u.Add(subscriptionorder.FieldDiscountAmount, v)
	return u
}

// SetPaymentMethod sets the "payment_method" field.
func (u *SubscriptionOrderUpsert) SetPaymentMethod(v string) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldPaymentMethod, v)
	return u
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdatePaymentMethod() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldPaymentMethod)
	return u
}

// SetStatus sets the "status" field.
func (u *SubscriptionOrderUpsert) SetStatus(v string) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateStatus() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldStatus)
	return u
}

// SetNotifyData sets the "notify_data" field.
func (u *SubscriptionOrderUpsert) SetNotifyData(v string) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldNotifyData, v)
	return u
}

// UpdateNotifyData sets the "notify_data" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateNotifyData() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldNotifyData)
	return u
}

// ClearNotifyData clears the value of the "notify_data" field.
func (u *SubscriptionOrderUpsert) ClearNotifyData() *SubscriptionOrderUpsert {
	u.SetNull(subscriptionorder.FieldNotifyData)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *SubscriptionOrderUpsert) SetPaidAt(v time.Time) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdatePaidAt() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *SubscriptionOrderUpsert) ClearPaidAt() *SubscriptionOrderUpsert {
	u.SetNull(subscriptionorder.FieldPaidAt)
	return u
}

// SetExpiredAt sets the "expired_at" field.
func (u *SubscriptionOrderUpsert) SetExpiredAt(v time.Time) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldExpiredAt, v)
	return u
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateExpiredAt() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldExpiredAt)
	return u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (u *SubscriptionOrderUpsert) ClearExpiredAt() *SubscriptionOrderUpsert {
	u.SetNull(subscriptionorder.FieldExpiredAt)
	return u
}

// SetActivatedAt sets the "activated_at" field.
func (u *SubscriptionOrderUpsert) SetActivatedAt(v time.Time) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldActivatedAt, v)
	return u
}

// UpdateActivatedAt sets the "activated_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateActivatedAt() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldActivatedAt)
	return u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (u *SubscriptionOrderUpsert) ClearActivatedAt() *SubscriptionOrderUpsert {
	u.SetNull(subscriptionorder.FieldActivatedAt)
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionOrderUpsert) SetSubscriptionID(v int64) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldSubscriptionID, v)
	return u
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateSubscriptionID() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldSubscriptionID)
	return u
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *SubscriptionOrderUpsert) AddSubscriptionID(v int64) *SubscriptionOrderUpsert {
	u.Add(subscriptionorder.FieldSubscriptionID, v)
	return u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *SubscriptionOrderUpsert) ClearSubscriptionID() *SubscriptionOrderUpsert {
	u.SetNull(subscriptionorder.FieldSubscriptionID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionOrderUpsertOne) UpdateNewValues() *SubscriptionOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionOrderUpsertOne) Ignore() *SubscriptionOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionOrderUpsertOne) DoNothing() *SubscriptionOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionOrderCreate.OnConflict
// documentation for more info.
func (u *SubscriptionOrderUpsertOne) Update(set func(*SubscriptionOrderUpsert)) *SubscriptionOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *SubscriptionOrderUpsertOne) SetOrderNo(v string) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateOrderNo() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetTradeNo sets the "trade_no" field.
func (u *SubscriptionOrderUpsertOne) SetTradeNo(v string) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetTradeNo(v)
	})
}

// UpdateTradeNo sets the "trade_no" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateTradeNo() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateTradeNo()
	})
}

// ClearTradeNo clears the value of the "trade_no" field.
func (u *SubscriptionOrderUpsertOne) ClearTradeNo() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearTradeNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionOrderUpsertOne) SetUserID(v int64) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateUserID() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionOrderUpsertOne) SetGroupID(v int64) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateGroupID() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateGroupID()
	})
}

// SetAmount sets the "amount" field.
func (u *SubscriptionOrderUpsertOne) SetAmount(v float64) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *SubscriptionOrderUpsertOne) AddAmount(v float64) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateAmount() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetOriginalPrice sets the "original_price" field.
func (u *SubscriptionOrderUpsertOne) SetOriginalPrice(v float64) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetOriginalPrice(v)
	})
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *SubscriptionOrderUpsertOne) AddOriginalPrice(v float64) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.AddOriginalPrice(v)
	})
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateOriginalPrice() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateOriginalPrice()
	})
}

// SetDiscountAmount sets the "discount_amount" field.
func (u *SubscriptionOrderUpsertOne) SetDiscountAmount(v float64) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetDiscountAmount(v)
	})
}

// AddDiscountAmount adds v to the "discount_amount" field.
func (u *SubscriptionOrderUpsertOne) AddDiscountAmount(v float64) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.AddDiscountAmount(v)
	})
}

// UpdateDiscountAmount sets the "discount_amount" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateDiscountAmount() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateDiscountAmount()
	})
}

// SetPaymentMethod sets the "payment_method" field.
func (u *SubscriptionOrderUpsertOne) SetPaymentMethod(v string) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaymentMethod(v)
	})
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdatePaymentMethod() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaymentMethod()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionOrderUpsertOne) SetStatus(v string) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateStatus() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetNotifyData sets the "notify_data" field.
func (u *SubscriptionOrderUpsertOne) SetNotifyData(v string) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetNotifyData(v)
	})
}

// UpdateNotifyData sets the "notify_data" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateNotifyData() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateNotifyData()
	})
}

// ClearNotifyData clears the value of the "notify_data" field.
func (u *SubscriptionOrderUpsertOne) ClearNotifyData() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearNotifyData()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *SubscriptionOrderUpsertOne) SetPaidAt(v time.Time) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdatePaidAt() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *SubscriptionOrderUpsertOne) ClearPaidAt() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetExpiredAt sets the "expired_at" field.
func (u *SubscriptionOrderUpsertOne) SetExpiredAt(v time.Time) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetExpiredAt(v)
	})
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateExpiredAt() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateExpiredAt()
	})
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (u *SubscriptionOrderUpsertOne) ClearExpiredAt() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearExpiredAt()
	})
}

// SetActivatedAt sets the "activated_at" field.
func (u *SubscriptionOrderUpsertOne) SetActivatedAt(v time.Time) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetActivatedAt(v)
	})
}

// UpdateActivatedAt sets the "activated_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateActivatedAt() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateActivatedAt()
	})
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (u *SubscriptionOrderUpsertOne) ClearActivatedAt() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearActivatedAt()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionOrderUpsertOne) SetSubscriptionID(v int64) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetSubscriptionID(v)
	})
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *SubscriptionOrderUpsertOne) AddSubscriptionID(v int64) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.AddSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateSubscriptionID() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateSubscriptionID()
	})
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *SubscriptionOrderUpsertOne) ClearSubscriptionID() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearSubscriptionID()
	})
}

// Exec executes the query.
func (u *SubscriptionOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionOrderCreateBulk is the builder for creating many SubscriptionOrder entities in bulk.
type SubscriptionOrderCreateBulk struct {
	config
	err      error
	builders []*SubscriptionOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionOrder entities in the database.
func (_c *SubscriptionOrderCreateBulk) Save(ctx context.Context) ([]*SubscriptionOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionOrderCreateBulk) SaveX(ctx context.Context) []*SubscriptionOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionOrderUpsert) {
//			SetOrderNo(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionOrderUpsertBulk {
	_c.conflict = opts
	return &SubscriptionOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionOrderCreateBulk) OnConflictColumns(columns ...string) *SubscriptionOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionOrderUpsertBulk{
		create: _c,
	}
}

// SubscriptionOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionOrder nodes.
type SubscriptionOrderUpsertBulk struct {
	create *SubscriptionOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionOrderUpsertBulk) UpdateNewValues() *SubscriptionOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionOrderUpsertBulk) Ignore() *SubscriptionOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionOrderUpsertBulk) DoNothing() *SubscriptionOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionOrderCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionOrderUpsertBulk) Update(set func(*SubscriptionOrderUpsert)) *SubscriptionOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *SubscriptionOrderUpsertBulk) SetOrderNo(v string) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateOrderNo() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetTradeNo sets the "trade_no" field.
func (u *SubscriptionOrderUpsertBulk) SetTradeNo(v string) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetTradeNo(v)
	})
}

// UpdateTradeNo sets the "trade_no" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateTradeNo() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateTradeNo()
	})
}

// ClearTradeNo clears the value of the "trade_no" field.
func (u *SubscriptionOrderUpsertBulk) ClearTradeNo() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearTradeNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionOrderUpsertBulk) SetUserID(v int64) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateUserID() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionOrderUpsertBulk) SetGroupID(v int64) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateGroupID() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateGroupID()
	})
}

// SetAmount sets the "amount" field.
func (u *SubscriptionOrderUpsertBulk) SetAmount(v float64) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *SubscriptionOrderUpsertBulk) AddAmount(v float64) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateAmount() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetOriginalPrice sets the "original_price" field.
func (u *SubscriptionOrderUpsertBulk) SetOriginalPrice(v float64) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetOriginalPrice(v)
	})
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *SubscriptionOrderUpsertBulk) AddOriginalPrice(v float64) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.AddOriginalPrice(v)
	})
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateOriginalPrice() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateOriginalPrice()
	})
}

// SetDiscountAmount sets the "discount_amount" field.
func (u *SubscriptionOrderUpsertBulk) SetDiscountAmount(v float64) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetDiscountAmount(v)
	})
}

// AddDiscountAmount adds v to the "discount_amount" field.
func (u *SubscriptionOrderUpsertBulk) AddDiscountAmount(v float64) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.AddDiscountAmount(v)
	})
}

// UpdateDiscountAmount sets the "discount_amount" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateDiscountAmount() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateDiscountAmount()
	})
}

// SetPaymentMethod sets the "payment_method" field.
func (u *SubscriptionOrderUpsertBulk) SetPaymentMethod(v string) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaymentMethod(v)
	})
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdatePaymentMethod() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaymentMethod()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionOrderUpsertBulk) SetStatus(v string) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateStatus() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetNotifyData sets the "notify_data" field.
func (u *SubscriptionOrderUpsertBulk) SetNotifyData(v string) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetNotifyData(v)
	})
}

// UpdateNotifyData sets the "notify_data" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateNotifyData() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateNotifyData()
	})
}

// ClearNotifyData clears the value of the "notify_data" field.
func (u *SubscriptionOrderUpsertBulk) ClearNotifyData() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearNotifyData()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *SubscriptionOrderUpsertBulk) SetPaidAt(v time.Time) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdatePaidAt() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *SubscriptionOrderUpsertBulk) ClearPaidAt() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetExpiredAt sets the "expired_at" field.
func (u *SubscriptionOrderUpsertBulk) SetExpiredAt(v time.Time) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetExpiredAt(v)
	})
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateExpiredAt() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateExpiredAt()
	})
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (u *SubscriptionOrderUpsertBulk) ClearExpiredAt() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearExpiredAt()
	})
}

// SetActivatedAt sets the "activated_at" field.
func (u *SubscriptionOrderUpsertBulk) SetActivatedAt(v time.Time) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetActivatedAt(v)
	})
}

// UpdateActivatedAt sets the "activated_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateActivatedAt() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateActivatedAt()
	})
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (u *SubscriptionOrderUpsertBulk) ClearActivatedAt() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearActivatedAt()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionOrderUpsertBulk) SetSubscriptionID(v int64) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetSubscriptionID(v)
	})
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *SubscriptionOrderUpsertBulk) AddSubscriptionID(v int64) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.AddSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateSubscriptionID() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateSubscriptionID()
	})
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *SubscriptionOrderUpsertBulk) ClearSubscriptionID() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearSubscriptionID()
	})
}

// Exec executes the query.
func (u *SubscriptionOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
