// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SubscriptionOrderUpdate is the builder for updating SubscriptionOrder entities.
type SubscriptionOrderUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionOrderMutation
}

// Where appends a list predicates to the SubscriptionOrderUpdate builder.
func (_u *SubscriptionOrderUpdate) Where(ps ...predicate.SubscriptionOrder) *SubscriptionOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *SubscriptionOrderUpdate) SetOrderNo(v string) *SubscriptionOrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableOrderNo(v *string) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetTradeNo sets the "trade_no" field.
func (_u *SubscriptionOrderUpdate) SetTradeNo(v string) *SubscriptionOrderUpdate {
	_u.mutation.SetTradeNo(v)
	return _u
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableTradeNo(v *string) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetTradeNo(*v)
	}
	return _u
}

// ClearTradeNo clears the value of the "trade_no" field.
func (_u *SubscriptionOrderUpdate) ClearTradeNo() *SubscriptionOrderUpdate {
	_u.mutation.ClearTradeNo()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionOrderUpdate) SetUserID(v int64) *SubscriptionOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableUserID(v *int64) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionOrderUpdate) SetGroupID(v int64) *SubscriptionOrderUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableGroupID(v *int64) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *SubscriptionOrderUpdate) SetAmount(v float64) *SubscriptionOrderUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableAmount(v *float64) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *SubscriptionOrderUpdate) AddAmount(v float64) *SubscriptionOrderUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *SubscriptionOrderUpdate) SetOriginalPrice(v float64) *SubscriptionOrderUpdate {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableOriginalPrice(v *float64) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *SubscriptionOrderUpdate) AddOriginalPrice(v float64) *SubscriptionOrderUpdate {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// SetDiscountAmount sets the "discount_amount" field.
func (_u *SubscriptionOrderUpdate) SetDiscountAmount(v float64) *SubscriptionOrderUpdate {
	_u.mutation.ResetDiscountAmount()
	_u.mutation.SetDiscountAmount(v)
	return _u
}

// SetNillableDiscountAmount sets the "discount_amount" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableDiscountAmount(v *float64) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetDiscountAmount(*v)
	}
	return _u
}

// AddDiscountAmount adds value to the "discount_amount" field.
func (_u *SubscriptionOrderUpdate) AddDiscountAmount(v float64) *SubscriptionOrderUpdate {
	_u.mutation.AddDiscountAmount(v)
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *SubscriptionOrderUpdate) SetPaymentMethod(v string) *SubscriptionOrderUpdate {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillablePaymentMethod(v *string) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionOrderUpdate) SetStatus(v string) *SubscriptionOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableStatus(v *string) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotifyData sets the "notify_data" field.
func (_u *SubscriptionOrderUpdate) SetNotifyData(v string) *SubscriptionOrderUpdate {
	_u.mutation.SetNotifyData(v)
	return _u
}

// SetNillableNotifyData sets the "notify_data" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableNotifyData(v *string) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetNotifyData(*v)
	}
	return _u
}

// ClearNotifyData clears the value of the "notify_data" field.
func (_u *SubscriptionOrderUpdate) ClearNotifyData() *SubscriptionOrderUpdate {
	_u.mutation.ClearNotifyData()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *SubscriptionOrderUpdate) SetPaidAt(v time.Time) *SubscriptionOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillablePaidAt(v *time.Time) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *SubscriptionOrderUpdate) ClearPaidAt() *SubscriptionOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *SubscriptionOrderUpdate) SetExpiredAt(v time.Time) *SubscriptionOrderUpdate {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableExpiredAt(v *time.Time) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *SubscriptionOrderUpdate) ClearExpiredAt() *SubscriptionOrderUpdate {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetActivatedAt sets the "activated_at" field.
func (_u *SubscriptionOrderUpdate) SetActivatedAt(v time.Time) *SubscriptionOrderUpdate {
	_u.mutation.SetActivatedAt(v)
	return _u
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableActivatedAt(v *time.Time) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetActivatedAt(*v)
	}
	return _u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (_u *SubscriptionOrderUpdate) ClearActivatedAt() *SubscriptionOrderUpdate {
	_u.mutation.ClearActivatedAt()
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionOrderUpdate) SetSubscriptionID(v int64) *SubscriptionOrderUpdate {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableSubscriptionID(v *int64) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *SubscriptionOrderUpdate) AddSubscriptionID(v int64) *SubscriptionOrderUpdate {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *SubscriptionOrderUpdate) ClearSubscriptionID() *SubscriptionOrderUpdate {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionOrderUpdate) SetUser(v *User) *SubscriptionOrderUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SubscriptionOrderUpdate) SetGroup(v *Group) *SubscriptionOrderUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the SubscriptionOrderMutation object of the builder.
func (_u *SubscriptionOrderUpdate) Mutation() *SubscriptionOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionOrderUpdate) ClearUser() *SubscriptionOrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SubscriptionOrderUpdate) ClearGroup() *SubscriptionOrderUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionOrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionOrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := subscriptionorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TradeNo(); ok {
		if err := subscriptionorder.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentMethod(); ok {
		if err := subscriptionorder.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.payment_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionOrder.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionOrder.group"`)
	}
	return nil
}

func (_u *SubscriptionOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionorder.Table, subscriptionorder.Columns, sqlgraph.NewFieldSpec(subscriptionorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(subscriptionorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradeNo(); ok {
		_spec.SetField(subscriptionorder.FieldTradeNo, field.TypeString, value)
	}
	if _u.mutation.TradeNoCleared() {
		_spec.ClearField(subscriptionorder.FieldTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(subscriptionorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(subscriptionorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(subscriptionorder.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(subscriptionorder.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DiscountAmount(); ok {
		_spec.SetField(subscriptionorder.FieldDiscountAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountAmount(); ok {
		_spec.AddField(subscriptionorder.FieldDiscountAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.NotifyData(); ok {
		_spec.SetField(subscriptionorder.FieldNotifyData, field.TypeString, value)
	}
	if _u.mutation.NotifyDataCleared() {
		_spec.ClearField(subscriptionorder.FieldNotifyData, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(subscriptionorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(subscriptionorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(subscriptionorder.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(subscriptionorder.FieldExpiredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ActivatedAt(); ok {
		_spec.SetField(subscriptionorder.FieldActivatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivatedAtCleared() {
		_spec.ClearField(subscriptionorder.FieldActivatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(subscriptionorder.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(subscriptionorder.FieldSubscriptionID, field.TypeInt64, value)
	}
	if _u.mutation.SubscriptionIDCleared() {
		_spec.ClearField(subscriptionorder.FieldSubscriptionID, field.TypeInt64)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.UserTable,
			Columns: []string{subscriptionorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.UserTable,
			Columns: []string{subscriptionorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.GroupTable,
			Columns: []string{subscriptionorder.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.GroupTable,
			Columns: []string{subscriptionorder.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionOrderUpdateOne is the builder for updating a single SubscriptionOrder entity.
type SubscriptionOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionOrderMutation
}

// SetOrderNo sets the "order_no" field.
func (_u *SubscriptionOrderUpdateOne) SetOrderNo(v string) *SubscriptionOrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableOrderNo(v *string) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetTradeNo sets the "trade_no" field.
func (_u *SubscriptionOrderUpdateOne) SetTradeNo(v string) *SubscriptionOrderUpdateOne {
	_u.mutation.SetTradeNo(v)
	return _u
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableTradeNo(v *string) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetTradeNo(*v)
	}
	return _u
}

// ClearTradeNo clears the value of the "trade_no" field.
func (_u *SubscriptionOrderUpdateOne) ClearTradeNo() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearTradeNo()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionOrderUpdateOne) SetUserID(v int64) *SubscriptionOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableUserID(v *int64) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionOrderUpdateOne) SetGroupID(v int64) *SubscriptionOrderUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableGroupID(v *int64) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *SubscriptionOrderUpdateOne) SetAmount(v float64) *SubscriptionOrderUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableAmount(v *float64) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *SubscriptionOrderUpdateOne) AddAmount(v float64) *SubscriptionOrderUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *SubscriptionOrderUpdateOne) SetOriginalPrice(v float64) *SubscriptionOrderUpdateOne {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableOriginalPrice(v *float64) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *SubscriptionOrderUpdateOne) AddOriginalPrice(v float64) *SubscriptionOrderUpdateOne {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// SetDiscountAmount sets the "discount_amount" field.
func (_u *SubscriptionOrderUpdateOne) SetDiscountAmount(v float64) *SubscriptionOrderUpdateOne {
	_u.mutation.ResetDiscountAmount()
	_u.mutation.SetDiscountAmount(v)
	return _u
}

// SetNillableDiscountAmount sets the "discount_amount" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableDiscountAmount(v *float64) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetDiscountAmount(*v)
	}
	return _u
}

// AddDiscountAmount adds value to the "discount_amount" field.
func (_u *SubscriptionOrderUpdateOne) AddDiscountAmount(v float64) *SubscriptionOrderUpdateOne {
	_u.mutation.AddDiscountAmount(v)
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *SubscriptionOrderUpdateOne) SetPaymentMethod(v string) *SubscriptionOrderUpdateOne {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillablePaymentMethod(v *string) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionOrderUpdateOne) SetStatus(v string) *SubscriptionOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableStatus(v *string) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotifyData sets the "notify_data" field.
func (_u *SubscriptionOrderUpdateOne) SetNotifyData(v string) *SubscriptionOrderUpdateOne {
	_u.mutation.SetNotifyData(v)
	return _u
}

// SetNillableNotifyData sets the "notify_data" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableNotifyData(v *string) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetNotifyData(*v)
	}
	return _u
}

// ClearNotifyData clears the value of the "notify_data" field.
func (_u *SubscriptionOrderUpdateOne) ClearNotifyData() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearNotifyData()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *SubscriptionOrderUpdateOne) SetPaidAt(v time.Time) *SubscriptionOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillablePaidAt(v *time.Time) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *SubscriptionOrderUpdateOne) ClearPaidAt() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *SubscriptionOrderUpdateOne) SetExpiredAt(v time.Time) *SubscriptionOrderUpdateOne {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableExpiredAt(v *time.Time) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *SubscriptionOrderUpdateOne) ClearExpiredAt() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetActivatedAt sets the "activated_at" field.
func (_u *SubscriptionOrderUpdateOne) SetActivatedAt(v time.Time) *SubscriptionOrderUpdateOne {
	_u.mutation.SetActivatedAt(v)
	return _u
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableActivatedAt(v *time.Time) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetActivatedAt(*v)
	}
	return _u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (_u *SubscriptionOrderUpdateOne) ClearActivatedAt() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearActivatedAt()
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionOrderUpdateOne) SetSubscriptionID(v int64) *SubscriptionOrderUpdateOne {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableSubscriptionID(v *int64) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *SubscriptionOrderUpdateOne) AddSubscriptionID(v int64) *SubscriptionOrderUpdateOne {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *SubscriptionOrderUpdateOne) ClearSubscriptionID() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionOrderUpdateOne) SetUser(v *User) *SubscriptionOrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SubscriptionOrderUpdateOne) SetGroup(v *Group) *SubscriptionOrderUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the SubscriptionOrderMutation object of the builder.
func (_u *SubscriptionOrderUpdateOne) Mutation() *SubscriptionOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionOrderUpdateOne) ClearUser() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SubscriptionOrderUpdateOne) ClearGroup() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the SubscriptionOrderUpdate builder.
func (_u *SubscriptionOrderUpdateOne) Where(ps ...predicate.SubscriptionOrder) *SubscriptionOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionOrderUpdateOne) Select(field string, fields ...string) *SubscriptionOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionOrder entity.
func (_u *SubscriptionOrderUpdateOne) Save(ctx context.Context) (*SubscriptionOrder, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionOrderUpdateOne) SaveX(ctx context.Context) *SubscriptionOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionOrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := subscriptionorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TradeNo(); ok {
		if err := subscriptionorder.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentMethod(); ok {
		if err := subscriptionorder.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.payment_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionOrder.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionOrder.group"`)
	}
	return nil
}

func (_u *SubscriptionOrderUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionorder.Table, subscriptionorder.Columns, sqlgraph.NewFieldSpec(subscriptionorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionorder.FieldID)
		for _, f := range fields {
			if !subscriptionorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(subscriptionorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradeNo(); ok {
		_spec.SetField(subscriptionorder.FieldTradeNo, field.TypeString, value)
	}
	if _u.mutation.TradeNoCleared() {
		_spec.ClearField(subscriptionorder.FieldTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(subscriptionorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(subscriptionorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(subscriptionorder.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(subscriptionorder.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DiscountAmount(); ok {
		_spec.SetField(subscriptionorder.FieldDiscountAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountAmount(); ok {
		_spec.AddField(subscriptionorder.FieldDiscountAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.NotifyData(); ok {
		_spec.SetField(subscriptionorder.FieldNotifyData, field.TypeString, value)
	}
	if _u.mutation.NotifyDataCleared() {
		_spec.ClearField(subscriptionorder.FieldNotifyData, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(subscriptionorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(subscriptionorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(subscriptionorder.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(subscriptionorder.FieldExpiredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ActivatedAt(); ok {
		_spec.SetField(subscriptionorder.FieldActivatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivatedAtCleared() {
		_spec.ClearField(subscriptionorder.FieldActivatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(subscriptionorder.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(subscriptionorder.FieldSubscriptionID, field.TypeInt64, value)
	}
	if _u.mutation.SubscriptionIDCleared() {
		_spec.ClearField(subscriptionorder.FieldSubscriptionID, field.TypeInt64)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.UserTable,
			Columns: []string{subscriptionorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.UserTable,
			Columns: []string{subscriptionorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.GroupTable,
			Columns: []string{subscriptionorder.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.GroupTable,
			Columns: []string{subscriptionorder.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
