// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SubscriptionOrder is the model entity for the SubscriptionOrder schema.
type SubscriptionOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// OrderNo holds the value of the "order_no" field.
	OrderNo string `json:"order_no,omitempty"`
	// TradeNo holds the value of the "trade_no" field.
	TradeNo *string `json:"trade_no,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// OriginalPrice holds the value of the "original_price" field.
	OriginalPrice float64 `json:"original_price,omitempty"`
	// DiscountAmount holds the value of the "discount_amount" field.
	DiscountAmount float64 `json:"discount_amount,omitempty"`
	// PaymentMethod holds the value of the "payment_method" field.
	PaymentMethod string `json:"payment_method,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// NotifyData holds the value of the "notify_data" field.
	NotifyData *string `json:"notify_data,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// ExpiredAt holds the value of the "expired_at" field.
	ExpiredAt *time.Time `json:"expired_at,omitempty"`
	// ActivatedAt holds the value of the "activated_at" field.
	ActivatedAt *time.Time `json:"activated_at,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID *int64 `json:"subscription_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionOrderQuery when eager-loading is set.
	Edges        SubscriptionOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionOrderEdges holds the relations/edges for other nodes in the graph.
type SubscriptionOrderEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionOrderEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionOrderEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionorder.FieldAmount, subscriptionorder.FieldOriginalPrice, subscriptionorder.FieldDiscountAmount:
			values[i] = new(sql.NullFloat64)
		case subscriptionorder.FieldID, subscriptionorder.FieldUserID, subscriptionorder.FieldGroupID, subscriptionorder.FieldSubscriptionID:
			values[i] = new(sql.NullInt64)
		case subscriptionorder.FieldOrderNo, subscriptionorder.FieldTradeNo, subscriptionorder.FieldPaymentMethod, subscriptionorder.FieldStatus, subscriptionorder.FieldNotifyData:
			values[i] = new(sql.NullString)
		case subscriptionorder.FieldCreatedAt, subscriptionorder.FieldPaidAt, subscriptionorder.FieldExpiredAt, subscriptionorder.FieldActivatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionOrder fields.
func (_m *SubscriptionOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionorder.FieldOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_no", values[i])
			} else if value.Valid {
				_m.OrderNo = value.String
			}
		case subscriptionorder.FieldTradeNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trade_no", values[i])
			} else if value.Valid {
				_m.TradeNo = new(string)
				*_m.TradeNo = value.String
			}
		case subscriptionorder.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case subscriptionorder.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case subscriptionorder.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case subscriptionorder.FieldOriginalPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field original_price", values[i])
			} else if value.Valid {
				_m.OriginalPrice = value.Float64
			}
		case subscriptionorder.FieldDiscountAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field discount_amount", values[i])
			} else if value.Valid {
				_m.DiscountAmount = value.Float64
			}
		case subscriptionorder.FieldPaymentMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_method", values[i])
			} else if value.Valid {
				_m.PaymentMethod = value.String
			}
		case subscriptionorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case subscriptionorder.FieldNotifyData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notify_data", values[i])
			} else if value.Valid {
				_m.NotifyData = new(string)
				*_m.NotifyData = value.String
			}
		case subscriptionorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionorder.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case subscriptionorder.FieldExpiredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expired_at", values[i])
			} else if value.Valid {
				_m.ExpiredAt = new(time.Time)
				*_m.ExpiredAt = value.Time
			}
		case subscriptionorder.FieldActivatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field activated_at", values[i])
			} else if value.Valid {
				_m.ActivatedAt = new(time.Time)
				*_m.ActivatedAt = value.Time
			}
		case subscriptionorder.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = new(int64)
				*_m.SubscriptionID = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionOrder.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the SubscriptionOrder entity.
func (_m *SubscriptionOrder) QueryUser() *UserQuery {
	return NewSubscriptionOrderClient(_m.config).QueryUser(_m)
}

// QueryGroup queries the "group" edge of the SubscriptionOrder entity.
func (_m *SubscriptionOrder) QueryGroup() *GroupQuery {
	return NewSubscriptionOrderClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this SubscriptionOrder.
// Note that you need to call SubscriptionOrder.Unwrap() before calling this method if this SubscriptionOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionOrder) Update() *SubscriptionOrderUpdateOne {
	return NewSubscriptionOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionOrder) Unwrap() *SubscriptionOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionOrder) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("order_no=")
	builder.WriteString(_m.OrderNo)
	builder.WriteString(", ")
	if v := _m.TradeNo; v != nil {
		builder.WriteString("trade_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("original_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.OriginalPrice))
	builder.WriteString(", ")
	builder.WriteString("discount_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiscountAmount))
	builder.WriteString(", ")
	builder.WriteString("payment_method=")
	builder.WriteString(_m.PaymentMethod)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.NotifyData; v != nil {
		builder.WriteString("notify_data=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiredAt; v != nil {
		builder.WriteString("expired_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ActivatedAt; v != nil {
		builder.WriteString("activated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SubscriptionID; v != nil {
		builder.WriteString("subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionOrders is a parsable slice of SubscriptionOrder.
type SubscriptionOrders []*SubscriptionOrder
